export const mailoutBox = [
  {
    id: "1",
    main: "/mailout/item1/main.jpg",
    image1: "/mailout/item1/defult.jpg",
    image2: "/mailout/item1/2nd design.jpg",
    image3: "/mailout/item1/3rd design.jpg",
    image4: "/mailout/item1/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card one",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "2",
    main: "/mailout/item2/main.jpg",
    image1: "/mailout/item2/defualt design.jpg",
    image2: "/mailout/item2/2nd design.jpg",
    image3: "/mailout/item2/3rd design.jpg",
    image4: "/mailout/item2/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "3",
    main: "/mailout/item3/main.jpg",
    image1: "/mailout/item3/defulat design.jpg",
    image2: "/mailout/item3/2nd design.jpg",
    image3: "/mailout/item3/3rd design.jpg",
    image4: "/mailout/item3/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "4",
    main: "/mailout/item4/main.jpg",
    image1: "/mailout/item4/defult.jpg",
    image2: "/mailout/item4/2nd design.jpg",
    image3: "/mailout/item4/3rd design.jpg",
    image4: "/mailout/item4/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "5",
    main: "/mailout/item5/main.jpg",
    image1: "/mailout/item5/defualt design.jpg",
    image2: "/mailout/item5/2nd design.jpg",
    image3: "/mailout/item5/3rd design.jpg",
    image4: "/mailout/item5/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "6",
    main: "/mailout/item6/main.jpg",
    image1: "/mailout/item6/defult design.jpg",
    image2: "/mailout/item6/2nd design.jpg",
    image3: "/mailout/item6/3rd design.jpg",
    image4: "/mailout/item6/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "7",
    main: "/mailout/item7/main.jpg",
    image1: "/mailout/item7/defult design.jpg",
    image2: "/mailout/item7/2nd design.jpg",
    image3: "/mailout/item7/3rd design.jpg",
    image4: "/mailout/item7/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "8",
    main: "/mailout/item8/main.jpg",
    image1: "/mailout/item8/defualt design.jpg",
    image2: "/mailout/item8/2nd design.jpg",
    image3: "/mailout/item8/3rd design.jpg",
    image4: "/mailout/item8/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
  {
    id: "9",
    main: "/mailout/item9/main.jpg",
    image1: "/mailout/item9/defult design.jpg",
    image2: "/mailout/item9/2nd design.jpg",
    image3: "/mailout/item9/3rd design.jpg",
    image4: "/mailout/item9/4th design.jpg",
    backPart: "/mailout/Pink Bordered Breakfast Invitation.png",
    name: "Beweddy Card two",
    color: ["red", "green", "blue"],
    decription:
      "A better way to think of EmailJS in terms of security is not as a service that allows you to send email from Javascript, but rather as a service that allows yo",
  },
];
