const Banner = () => {
  return (
    <div className="container py-10 mx-auto uppercase">
      <p className="text-left md:text-justify">
        PLEASE READ THIS DOCUMENT CAREFULLY BEFORE ACCESSING OR USING OUR
        WEBSITE. BY ACCESSING OR USING OUR WEBSITE, YOU AGREE TO BE BOUND BY THE
        TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT WISH TO BE BOUND BY
        THESE TERMS AND CONDITIONS, YOU MAY NOT ACCESS OR USE OUR WEBSITE. IF
        YOU DO NOT UNDERSTAND THESE TERMS AND CONDITIONS, DO NOT USE OUR
        WEBSITE. WE MAY MODIFY THIS AGREEMENT AT ANY TIME WITHOUT INDIVIDUAL,
        SPECIFIC NOTICE TO YOU, AND SUCH MODIFICATIONS SHALL BE EFFECTIVE
        IMMEDIATELY UPON POSTING OF THE MODIFIED AGREEMENT ON OUR WEBSITE. YOU
        AGREE TO REVIEW THE AGREEMENT PERIODICALLY TO BE AWARE OF SUCH
        MODIFICATIONS AND YOUR CONTINUED ACCESS OR USE OF OUR WEBSITE AFTER SUCH
        NOTICE SHALL BE DEEMED YOUR CONCLUSIVE ACCEPTANCE OF THE MODIFIED
        AGREEMENT, INCLUDING ANY AND ALL MODIFICATIONS, ADDITIONS, DELETIONS, OR
        OTHER CHANGES.
      </p>
      <p className="pt-5 text-left md:text-justify">
        OUR WEBSITE AND CONTENT ARE PROVIDED ON AN ‘AS IS’ BASIS WITHOUT ANY
        WARRANTIES OF ANY KIND. OUR WEBSITE AND ITS SUPPLIERS, TO THE FULLEST
        EXTENT PERMITTED BY LAW, DISCLAIM ALL WARRANTIES, INCLUDING (BUT NOT
        LIMITED TO) THE WARRANTY OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD
        PARTIES RIGHTS, AND THE WARRANTY OF FITNESS FOR PARTICULAR PURPOSE. OUR
        WEBSITE AND ITS SUPPLIERS MAKE NO WARRANTIES ABOUT THE ACCURACY,
        RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE CONTENT, SERVICES,
        SOFTWARE TEXT, GRAPHICS, AND LINKS.
      </p>
    </div>
  );
};

export default Banner;
